#!/bin/bash
set -e

if [[ -n $1 && $1 == 0 ]]; then
	shift; set -x
	sudo chroot rootfs \
		/usr/bin/env -i HOME=/root \
		TERM=$TERM PATH=/usr/bin:/usr/sbin \
		/bin/bash --login -c "$*"
else
	sudo chroot rootfs \
		/usr/bin/env -i HOME=/root \
		TERM=$TERM PATH=/usr/bin:/usr/sbin \
		/bin/bash --login -c "su builder -c 'cd /build; $*'"
fi
